# Generated by Django 3.2 on 2023-02-05 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
    ]
